"use client";
import Link from "next/link";
import { useState } from "react";
import { CalendarIcon,CheckIcon,MapPinIcon,UsersIcon,LockIcon } from "@/components/icons";
import { useDemoSession } from "@/components/demo-session";
export default function MissionPage(){
 const {activeKey,profile}=useDemoSession(); const[accepted,setAccepted]=useState(false); const[present,setPresent]=useState(false);
 if(activeKey!=="benevole") return <section className="roleDenied"><div className="roleDeniedIcon"><LockIcon/></div><p className="overline">ACCÈS CONTEXTUEL</p><h1>Cette page appartient à l'espace Bénévole.</h1><p>Vous êtes connecté comme <strong>{profile.name}</strong> ({profile.label}). La plateforme n'affiche pas les missions bénévoles dans ce contexte.</p><div><Link className="button buttonPrimary" href={profile.route}>Retour à mon espace {profile.label}</Link><Link className="button buttonSecondary" href="/connexion">Changer de compte</Link></div></section>;
 return <section><div className="missionHero"><div className="missionHeroContent"><span className="missionType">MISSION BÉNÉVOLE · CAMILLE MARTIN</span><h1>Accueil public — Parcours d'ouverture</h1><p>Accueillir, orienter et informer les publics lors d'un temps fort de Bourges 2028.</p><div className="missionHeroMeta"><span><CalendarIcon/>12 février 2028 · 16h00–21h00</span><span><MapPinIcon/>Maison de la Culture</span><span><UsersIcon/>5 places restantes sur 18</span></div></div><div className="missionHeroDate"><strong>12</strong><span>FÉVRIER</span><small>2028</small></div></div><div className="missionProGrid"><div className="missionBody"><article className="panelPro"><p className="overline">VOTRE RÔLE</p><h2>Ce que vous ferez</h2><p className="lead">Vous êtes le premier point de contact des visiteurs. Vous facilitez leur arrivée, leur orientation et leur compréhension du programme.</p></article></div><aside className="missionActionCard"><p className="overline">PARTICIPATION DE CAMILLE</p><h2>{present?"Présence confirmée":accepted?"Mission réservée":"Prête à participer ?"}</h2><ol className="stepperPro"><li className="done"><span><CheckIcon/></span><div><strong>Mission consultée</strong><small>Briefing lu</small></div></li><li className={accepted?"done":"active"}><span>{accepted?<CheckIcon/>:"2"}</span><div><strong>Acceptation</strong><small>Confirmation numérique</small></div></li><li className={present?"done":accepted?"active":""}><span>{present?<CheckIcon/>:"3"}</span><div><strong>Check-in</strong><small>Mobile ou borne</small></div></li></ol>{!accepted?<button className="button buttonPrimary full" onClick={()=>setAccepted(true)}>Accepter cette mission</button>:!present?<button className="button buttonPrimary full" onClick={()=>setPresent(true)}>Simuler le check-in</button>:<div className="confirmationBox"><CheckIcon/><span>Présence enregistrée</span></div>}</aside></div></section>
}
