"use client";
import { useRef, useState } from "react";
import { ActivityIcon, CheckIcon, CloudIcon, DatabaseIcon, ServerIcon } from "@/components/icons";
type Status="healthy"|"detecting"|"degraded"|"switching"|"restored";
export default function IncidentPage(){const[status,setStatus]=useState<Status>("healthy");const[node,setNode]=useState<"A"|"B">("A");const[elapsed,setElapsed]=useState(0);const[running,setRunning]=useState(false);const[logs,setLogs]=useState([{t:"14:52:00",level:"OK",text:"Health checks A/B nominaux"}]);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);
const run=()=>{timers.current.forEach(clearTimeout);setRunning(true);setElapsed(0);setNode("A");setStatus("detecting");setLogs([{t:"T+00s",level:"INFO",text:"Simulation : perte du nœud A injectée"}]);const events: Array<[number, number, Status, string, string]>=[[1000,1,"degraded","WARN","Health check A en échec (1/3)"],[3000,3,"degraded","WARN","Seuil atteint · A retiré du pool"],[5000,5,"switching","INFO","Routage du trafic vers B"],[7000,7,"restored","OK","Nœud B sert 100 % du trafic"],[8000,8,"restored","OK","Service nominal · alerte clôturée"]];events.forEach(([d,s,st,l,t])=>timers.current.push(setTimeout(()=>{setElapsed(s);setStatus(st);if(s>=7)setNode("B");setLogs(p=>[...p,{t:`T+0${s}s`,level:l,text:t}]);if(s===8)setRunning(false)},d)))};
return <section className="opsPage"><div className="appPageTitle"><div><p className="overline">RÉSILIENCE & EXPLOITATION</p><h1>Voir la panne. Comprendre la bascule.</h1><p>Une simulation explicite de la perte isolée d'un nœud applicatif.</p></div><span className="demoTag">SIMULATION · PAS UN TEST PRA RÉEL</span></div>
<div className="opsSummary"><div><small>Disponibilité cible</small><strong>99,5 %</strong></div><div><small>État du service</small><strong className={status==="restored"||status==="healthy"?"stateOk":"stateWarn"}><span className="statusDot"/>{status==="healthy"?"Nominal":status==="restored"?"Rétabli":"Dégradé"}</strong></div><div><small>Nœud servant</small><strong>{node}</strong></div><div><small>Bascule simulée</small><strong>{elapsed||"—"}{elapsed?" s":""}</strong></div></div>
<div className="opsGrid"><article className="topologyPanel"><div className="panelProHeader"><div><p className="overline">TOPOLOGIE CIBLE</p><h2>Deux nœuds, un service</h2></div><span className="liveChip"><span className="statusDot"/> Observé</span></div><div className="topology"><div className="topologyIngress"><CloudIcon/><div><strong>Entrée HTTPS</strong><span>répartiteur + health checks</span></div></div><div className="connector vertical"/><div className="nodePair"><div className={`serverNode ${node==="A"&&status!=="degraded"?"active":""} ${status==="degraded"&&node==="A"?"failed":""}`}><ServerIcon/><div><strong>Nœud A</strong><span>{status==="degraded"&&node==="A"?"unhealthy":node==="A"?"serving":"standby"}</span></div><i/></div><div className={`serverNode ${node==="B"?"active":""}`}><ServerIcon/><div><strong>Nœud B</strong><span>{node==="B"?"serving":"standby"}</span></div><i/></div></div><div className="connector vertical"/><div className="storeRow"><div><DatabaseIcon/><span><strong>PostgreSQL</strong><small>données persistantes</small></span></div><div><CloudIcon/><span><strong>Object Storage</strong><small>documents hors nœuds</small></span></div><div><ActivityIcon/><span><strong>Supervision</strong><small>externe au service</small></span></div></div></div></article>
<aside className="simulationPanel"><div className="simTimer"><strong>{String(elapsed).padStart(2,"0")}</strong><span>secondes</span></div><div className="simStatus"><span className={`statusLamp ${status}`}/><div><small>État courant</small><strong>{status==="healthy"?"Prêt":status==="detecting"?"Détection":status==="degraded"?"Nœud A isolé":status==="switching"?"Bascule":status==="restored"?"Service rétabli":""}</strong></div></div><button className="button buttonPrimary full" onClick={run} disabled={running}>{running?"Simulation en cours…":"Simuler la perte du nœud A"}</button><p>Objectif du scénario : montrer la mécanique de détection et de routage. La cible &lt; 60 s du mémoire ne constitue pas un RTO global.</p></aside></div>
<div className="opsBottom"><article className="panelPro"><div className="panelProHeader"><div><p className="overline">CHRONOLOGIE</p><h2>Journal d'incident</h2></div></div><div className="logPro" aria-live="polite">{logs.map((l,i)=><div key={i}><code>{l.t}</code><span className={`logLevel ${l.level.toLowerCase()}`}>{l.level}</span><p>{l.text}</p></div>)}</div></article><article className="panelPro"><p className="overline">GARDE-FOUS</p><h2>Ce qui évite l'effet domino</h2><ul className="cleanList"><li><CheckIcon/>État applicatif non stocké sur le nœud</li><li><CheckIcon/>Stockage persistant hors serveurs web</li><li><CheckIcon/>Déploiement du même artefact sur A et B</li><li><CheckIcon/>Rollback préparé avant changement sensible</li><li><CheckIcon/>Supervision extérieure au service observé</li></ul></article></div></section>}
