"use client";
import { FormEvent, useState } from "react";
import { CheckIcon, LockIcon, ShieldIcon } from "@/components/icons";
export default function SecurityPage(){
  const [step,setStep]=useState<"login"|"otp"|"done">("login"); const [msg,setMsg]=useState("");
  const login=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setStep("otp");setMsg("Identité vérifiée. Second facteur requis pour ce rôle.")};
  const otp=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=String(new FormData(e.currentTarget).get("otp")||"");if(v==="202828"){setStep("done");setMsg("Authentification forte réussie. Session administrateur ouverte.")}else setMsg("Code incorrect. Code de démonstration : 202828")};
  return <section>
    <div className="appPageTitle"><div><p className="overline">SÉCURITÉ & GESTION DES DROITS</p><h1>Un accès privilégié doit être explicable.</h1><p>Le parcours montre ce que l'utilisateur voit et ce que la plateforme doit contrôler.</p></div><span className="demoTag">SIMULATION PÉDAGOGIQUE</span></div>
    <div className="securityProGrid">
      <article className="authProCard"><div className="authBrand"><span><ShieldIcon/></span><div><strong>Administration Bourges 2028</strong><small>Accès sécurisé</small></div></div>{step==="login"&&<form onSubmit={login}><div className="authHeading"><h2>Connexion</h2><p>Utilisez le compte de démonstration prérempli.</p></div><label>Adresse e-mail<input type="email" defaultValue="demo.admin@bourges2028.fr" required/></label><label>Mot de passe<div className="inputWithIcon"><LockIcon/><input type="password" defaultValue="Demo2028!" required/></div></label><button className="button buttonPrimary full">Continuer</button><p className="authFine">En production : politique de mot de passe, limitation des tentatives et session sécurisée.</p></form>}{step==="otp"&&<form onSubmit={otp}><div className="otpIcon"><LockIcon/></div><div className="authHeading centered"><h2>Vérification en deux étapes</h2><p>Saisissez le code de démonstration envoyé à l'administrateur.</p></div><div className="demoCode">Code démo : <strong>202828</strong></div><label>Code à 6 chiffres<input name="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="••••••" className="otpInput" required autoFocus/></label><button className="button buttonPrimary full">Vérifier l'identité</button><button className="textButton centeredButton" type="button" onClick={()=>setStep("login")}>Retour</button></form>}{step==="done"&&<div className="authSuccess"><div className="successCircle"><CheckIcon/></div><h2>Accès autorisé</h2><p>La session est ouverte avec le rôle <strong>Administrateur</strong>.</p><div className="sessionFacts"><span><small>Rôle</small><strong>ADMIN_BOURGES</strong></span><span><small>2FA</small><strong>Validé</strong></span><span><small>Session</small><strong>30 min</strong></span></div><button className="button buttonSecondary full" onClick={()=>{setStep("login");setMsg("")}}>Rejouer le scénario</button></div>}<p className="ariaMessage" aria-live="polite">{msg}</p></article>
      <div className="securityEvidence">
        <article className="panelPro"><p className="overline">CONTRÔLES ILLUSTRÉS</p><h2>Défense en profondeur</h2><div className="controlList">{[["RBAC serveur","Les droits sont évalués côté serveur, jamais uniquement dans l'interface."],["2FA privilégié","Le second facteur est imposé aux comptes à risque."],["Sessions","Expiration, renouvellement et révocation sont prévus."],["Traçabilité","Les actions sensibles produisent des événements d'audit."],["Uploads","Type, taille et contenu sont contrôlés avant stockage."],["Privacy by default","Le minimum de données est exposé selon le rôle."]].map(([t,d])=><div key={t}><span className="controlCheck"><CheckIcon/></span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div></article>
        <article className="auditPanel"><div className="panelProHeader"><div><p className="overline">JOURNAL D'AUDIT</p><h2>Derniers événements</h2></div><span className="liveChip"><span className="statusDot"/> Live</span></div><div className="auditRows"><div><code>14:52:08</code><span className="auditType auth">AUTH</span><p>Connexion admin réussie</p><small>192.0.2.14</small></div><div><code>14:51:44</code><span className="auditType read">READ</span><p>Consultation dossier #CRI-284</p><small>admin.demo</small></div><div><code>14:48:11</code><span className="auditType change">CHANGE</span><p>Statut dossier modifié</p><small>admin.demo</small></div></div></article>
      </div>
    </div>
  </section>
}
