"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { CheckIcon,ShieldIcon } from "@/components/icons";
import { useDemoSession } from "@/components/demo-session";

export default function ProfilPage(){
 const {activeKey,profile}=useDemoSession(); const [editing,setEditing]=useState(false); const [tab,setTab]=useState("Vue d’ensemble"); const [toast,setToast]=useState("");
 const details=useMemo(()=>({
  benevole:{section:"Engagement bénévole",cards:[["Disponibilités","Ven. soir · Samedi · Dim. après-midi"],["Missions réalisées","6 depuis l'inscription"],["Prochaine mission","12 fév. · Maison de la Culture"]],docs:["Autorisation_image.pdf","Attestation_benevolat.pdf"]},
  candidat:{section:"Candidature CRI",cards:[["Dossier","CRI-2026-084"],["Complétude","92 %"],["Échéance","18 octobre · 23:59"]],docs:["Budget_Projet.xlsx","Présentation_artistique.pdf","Attestation_partenaire.pdf"]},
  laureat:{section:"Projet lauréat",cards:[["Projet","Traversées"],["Convention","Signée"],["Prochain livrable","Note d'étape · 15 nov."]],docs:["Convention_signee.pdf","Budget_actualise.xlsx","Plan_production.pdf"]},
  jury:{section:"Habilitations jury",cards:[["Dossiers affectés","12"],["Évaluations terminées","5"],["Déclaration d'intérêts","À jour"]],docs:["Charte_jury.pdf","Declaration_interets.pdf"]}
 })[activeKey],[activeKey]);
 function save(){setEditing(false);setToast("Modifications enregistrées dans la démonstration");setTimeout(()=>setToast(""),2200)}
 return <div className="profileApp profileAppV6">{toast&&<div className="toastPro"><CheckIcon/>{toast}</div>}<aside className="profileRail"><div className="profileAccountCard"><div className="profileAvatar xl">{profile.initials}</div><div><strong>{profile.name}</strong><span>{profile.label}</span></div></div><div className="profileScore"><div><span>Profil complété</span><strong>{profile.completion}%</strong></div><div className="progressBar large"><span style={{width:`${profile.completion}%`}}/></div><small>{profile.status}</small></div><nav className="profileTabNav">{["Vue d’ensemble","Identité","Données métier","Documents","Préférences","Sécurité"].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"active":""}>{t}</button>)}</nav><Link className="button buttonSecondary full compact" href={profile.route}>Retour à mon espace</Link></aside>
 <main className="profileWorkspace"><header className="profileTopbar"><div><p className="overline">PROFIL · {profile.label}</p><h1>{profile.name}</h1><p>{profile.headline}. Cet écran change entièrement selon le compte connecté.</p></div><div className="profileActions">{editing?<><button className="button buttonSecondary" onClick={()=>setEditing(false)}>Annuler</button><button className="button buttonPrimary" onClick={save}>Enregistrer</button></>:<button className="button buttonPrimary" onClick={()=>setEditing(true)}>Modifier</button>}</div></header>
 <section className="identityHeroCard personaIdentity"><div className="identityHeroTop"><div className="profileAvatar huge">{profile.initials}</div><div><span className={`statusBadge ${profile.statusTone}`}>{profile.status}</span><h2>{profile.name}</h2><p>{profile.email} · {profile.phone}</p></div></div><div className="identityMeta"><div><small>Ville</small><strong>{profile.city}</strong></div><div><small>Rôle principal</small><strong>{profile.label}</strong></div><div><small>Rôles liés</small><strong>{profile.roles.join(" · ")}</strong></div></div></section>
 {tab==="Vue d’ensemble"&&<><section className="profileDashboardGrid">{details.cards.map(([a,b])=><article className="panelPro" key={a}><p className="overline">{details.section}</p><h2 className="miniHeading">{a}</h2><strong className="profileBigValue">{b}</strong></article>)}</section><section className="profileTwoCols"><article className="panelPro"><p className="overline">À PROPOS</p><h2>Informations utiles</h2><p>{profile.bio}</p><div className="skillsCloud">{profile.skills.map(s=><span key={s}>{s}</span>)}</div></article><article className="panelPro"><p className="overline">ACCÈS RAPIDE</p><h2>Continuer mon parcours</h2><div className="quickActions"><Link href={profile.route}>Ouvrir mon espace métier →</Link><Link href="/agenda">Consulter mon agenda →</Link></div></article></section></>}
 {tab==="Identité"&&<section className="panelPro profileSectionCard"><p className="overline">IDENTITÉ & CONTACT</p><h2>Coordonnées de {profile.name}</h2><div className="formGrid proFields"><label>Nom complet<input disabled={!editing} defaultValue={profile.name}/></label><label>E-mail<input disabled={!editing} defaultValue={profile.email}/></label><label>Téléphone<input disabled={!editing} defaultValue={profile.phone}/></label><label>Ville<input disabled={!editing} defaultValue={profile.city}/></label></div></section>}
 {tab==="Données métier"&&<section className="panelPro profileSectionCard"><p className="overline">{details.section}</p><h2>Données spécifiques à ce profil</h2><div className="businessDataGrid">{details.cards.map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><p className="contextExplanation">Un candidat ne voit pas de missions bénévoles ; un juré ne voit pas les données privées d'un bénévole ; un lauréat retrouve son suivi contractuel. Les interfaces et les données sont cloisonnées par rôle.</p></section>}
 {tab==="Documents"&&<section className="panelPro profileSectionCard"><p className="overline">DOCUMENTS</p><h2>Pièces de {profile.name}</h2><div className="documentRows">{details.docs.map(d=><div key={d}><span>{d}</span><b className="positive">Disponible</b></div>)}</div></section>}
 {tab==="Préférences"&&<section className="panelPro profileSectionCard"><p className="overline">PRÉFÉRENCES</p><h2>Notifications</h2><div className="settingsRows"><label><span><strong>E-mails métier</strong><span>Échéances, changements de statut et confirmations</span></span><input type="checkbox" defaultChecked/></label><label><span><strong>Notifications plateforme</strong><span>Activité liée à votre espace</span></span><input type="checkbox" defaultChecked/></label></div></section>}
 {tab==="Sécurité"&&<section className="panelPro profileSectionCard"><p className="overline">SÉCURITÉ</p><h2>Accès et traçabilité</h2><div className="securityCards"><div><ShieldIcon/><span><strong>Rôle actif</strong><span>{profile.label}</span></span><b>{activeKey==="jury"?"2FA activée":"Session standard"}</b></div><div><ShieldIcon/><span><strong>Isolation des données</strong><span>Accès limité aux données autorisées pour ce compte</span></span><b>Actif</b></div></div></section>}
 </main></div>
}
